#+TITLE: Doom Emacs Config
#+AUTHOR: Trigex

* User Information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Trigex"
      user-mail-address "trigex@waifu.club")
#+END_SRC

* Visual Configuration
** Font Configuration
#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 14)
      doom-variable-pitch-font (font-spec :family "IBM Plex Sans" :size 14))
(setq line-spacing 1.2)
#+END_SRC

** Prettify Symbols
#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode t)
#+END_SRC

** Theme
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-nord)
#+END_SRC

** Modeline
#+BEGIN_SRC emacs-lisp
(setq doom-modeline-buffer-file-name-style 'relative-from-project)
(setq doom-modeline-major-mode-icon t)
(setq doom-modeline-major-mode-color-icon t)
(setq doom-modeline-unicode-fallback t)
#+END_SRC

** Dashboard
#+BEGIN_SRC emacs-lisp
(setq fancy-splash-image "~/.doom.d/cirno-dash.png")
#+END_SRC

** Line Numbering
Relative line numbers are teh best.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC
** Beacon
Beacon highlights the cursor on window changes and when scrolling.
#+BEGIN_SRC emacs-lisp
(use-package! beacon
  :diminish beacon-mode
  :init
  (beacon-mode 1))
#+END_SRC
* Bindings & Controls
** Splits
Nicer split functionality that moves the cursor to the new split automatically.
#+BEGIN_SRC emacs-lisp
(defun split-and-follow-horizontally ()
  (interactive)
  (split-window-below)
  (balance-windows)
  (other-window 1))
(global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)
(defun split-and-follow-vertically ()
  (interactive)
  (split-window-right)
  (balance-windows)
  (other-window 1))
(global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+END_SRC
** Window Resizing
Subject to change, but I quite like these bindings for window resizing.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "s-C-l") 'shrink-window-horizontally)
(global-set-key (kbd "s-C-h") 'enlarge-window-horizontally)
(global-set-key (kbd "s-C-j") 'shrink-window)
(global-set-key (kbd "s-C-k") 'enlarge-window)
#+END_SRC

* Org
** General Configuration
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/Documents/org")
#+END_SRC
** Bullets
org-bullets gives headigs and such nice little bulllet points
#+BEGIN_SRC emacs-lisp
(use-package! org-bullets
  :init
  (add-hook 'org-mode-hook (org-bullets-mode 1)))
#+END_SRC
** Visual Window Switching
#+BEGIN_SRC emacs-lisp
(use-package! switch-window
  :config
  (setq switch-window-input-style 'minibuffer)
  (setq switch-window-increase 4)
  (setq switch-window-threshold 2)
  (setq switch-window-shortcut-style 'qwerty)
  (setq switch-window-qwerty-shortcuts '("h" "j" "k" "l"))
  :bind
  ([remap other-window] . switch-window))
#+END_SRC
* Applications
** Circe (IRC)
*** Server Setup
#+BEGIN_SRC emacs-lisp
(after! circe
  (set-irc-server! "clan-world"
    `(:tls t
      :port 5597
      :host "znc.termer.net"
      :server-buffer-name "clan-world"
      :nick "trigex"
      :pass ,(+pass-get-secret "IRC/ZNC/clan-world")))
  (set-irc-server! "Rizon"
     `(:tls t
       :port 5597
       :host "znc.termer.net"
       :server-buffer-name "Rizon"
       :nick "trigex"
       :pass ,(+pass-get-secret "IRC/ZNC/Rizon")))
  (set-irc-server! "Freenode"
     `(:tls t
       :port 5597
       :host "znc.termer.net"
       :server-buffer-name "Freenode"
       :nick "trigex"
       :pass ,(+pass-get-secret "IRC/ZNC/Freenode")))
  (circe-lagmon-mode))
#+END_SRC

*** Notifications
Get notifications on all messages from friends :)
#+BEGIN_SRC emacs-lisp
(after! circe-notifications
  (setq circe-notifications-watch-strings
        '("HeXa" "LeJustice" "termer" "HelloMrEdwards" "FM" "tas" "tas_" "sage" "sage8" "Sentaku-san" "zenhead" "tusoud" "starman" "blakkheim"))
  (add-hook 'circe-server-connected-hook 'enable-circe-notifications))
#+END_SRC

* Miscellaneous Functions
** Compile Literate Config
#+BEGIN_SRC emacs-lisp
(defun trigex-compile-config ()
  (interactive)
  (shell-command "$HOME/.emacs.d/bin/doom sync"))
#+END_SRC
